FROM geolambda-base:local

LABEL maintainer="Satelytics"
LABEL authors="Python 3.12 Lambda Layer"

ARG PYVERSION=3.12.7
# install Python to system and virtual environment in /tmp/venv
ENV \
    PATH=/tmp/venv/bin:$PATH

RUN \
    cd /tmp; \
    echo  ${PYVERSION} > /root/version; \
    wget https://www.python.org/ftp/python/${PYVERSION}/Python-${PYVERSION}.tgz; \
    tar xzf Python-${PYVERSION}.tgz; \
    cd Python-${PYVERSION}; \
    ./configure; \
    make -j$(nproc); \
    make install; \
    cd ..; \
    rm -rf Python-${PYVERSION}*; \
    /usr/local/bin/python3.12 -m venv /tmp/venv; \
    /tmp/venv/bin/pip install --upgrade pip setuptools wheel

COPY requirements-py312.txt ./requirements.txt
COPY requirements-pre-py312.txt ./requirements-pre.txt

RUN \
    /tmp/venv/bin/pip install -r requirements-pre.txt; \
    /tmp/venv/bin/pip install -r requirements.txt

# Install RIPP from local tar file (since we can't access S3 directly)
COPY latest.tgz ./
RUN tar xzf ./latest.tgz \
    && cd ripp \
    && /tmp/venv/bin/pip install PyYAML sh && /tmp/venv/bin/pip install . \
    && cd .. && rm -rf ripp latest.tgz

COPY bin/* /usr/local/bin/